
# Data Exploration and Preprocessing

In this tutorial we will use the San Diego Weather dataset included in the "daily_weather.csv" file.
We will explore and then preprocess the dataset, dealing with missing values.


We start by reading the csv file into a dataframe (make sure to give the correct path when you run this).

In [1]:
print(__doc__)

import numpy as np
import scipy as sp
import pandas as pd

from sklearn.preprocessing import Imputer

#read the csv into a dataframe
df = pd.read_csv('daily_weather.csv')

Automatically created module for IPython interactive environment

In [2]:
#print the contents of the dataframe
df

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
0,0,918.060000,74.822000,271.100000,2.080354,295.400000,2.863283,0.00,0.0,42.420000,36.160000
1,1,917.347688,71.403843,101.935179,2.443009,140.471548,3.533324,0.00,0.0,24.328697,19.426597
2,2,923.040000,60.638000,51.000000,17.067852,63.700000,22.100967,0.00,20.0,8.900000,14.460000
3,3,920.502751,70.138895,198.832133,4.337363,211.203341,5.190045,0.00,0.0,12.189102,12.742547
4,4,921.160000,44.294000,277.800000,1.856660,136.500000,2.863283,8.90,14730.0,92.410000,76.740000
5,5,915.300000,78.404000,182.800000,9.932014,189.000000,10.983375,0.02,170.0,35.130000,33.930000
6,6,915.598868,70.043304,177.875407,3.745587,186.606696,4.589632,0.00,0.0,10.657422,21.385657
7,7,918.070000,51.710000,242.400000,2.527742,271.600000,3.646212,0.00,0.0,80.470000,74.920000
8,8,920.080000,80.582000,40.700000,4.518619,63.000000,5.883152,0.00,0.0,29.580000,24.030000
9,9,915.010000,47.498000,163.100000,4.943637,195.900000,6.576604,0.00,0.0,88.600000,68.050000
10,10,919.650000,77.036000,70.600000,3.825167,85.500000,4.764682,0.00,0.0,22.070000,32.130000
11,11,915.640000,45.716000,241.600000,5.860783,265.800000,8.030615,0.55,1770.0,90.560000,79.090000
12,12,917.390000,49.784000,204.100000,1.275056,211.800000,2.013246,0.00,0.0,73.150000,58.430000
13,13,920.820000,62.438000,213.600000,2.617220,165.700000,3.310671,0.00,0.0,43.640000,27.990000
14,14,911.000000,86.432000,202.900000,1.207948,162.900000,1.677705,0.00,0.0,15.190000,24.370000
15,15,922.383131,70.865263,36.174175,1.847278,58.428632,2.529142,0.00,0.0,12.110889,14.801706
16,16,917.890000,NaN,169.200000,2.192201,196.800000,2.930391,0.00,0.0,48.990000,51.190000
17,17,916.915255,77.018961,234.539345,2.274725,229.474199,2.906513,0.00,0.0,21.031462,20.755683
18,18,918.800000,67.082000,176.100000,4.876529,183.400000,5.569981,0.00,0.0,18.900000,45.870000
19,19,922.040000,68.576000,58.300000,9.551734,81.900000,12.571603,0.00,0.0,7.540000,7.740000
20,20,919.992262,62.964383,54.799094,12.680436,74.254223,15.452306,0.00,0.0,18.809518,14.649909
21,21,917.230000,67.676000,177.800000,2.460634,93.200000,3.288302,0.00,0.0,40.640000,41.340000
22,22,921.125626,68.818772,71.799092,2.576538,95.472334,3.487444,0.00,0.0,11.742201,17.281161
23,23,920.350000,47.570000,192.100000,6.263432,205.700000,7.605596,0.00,0.0,54.550000,66.000000
24,24,921.788229,71.659572,217.405520,1.946447,253.758003,2.719712,0.00,0.0,11.194250,16.331716
25,25,918.030000,50.666000,128.900000,2.527742,117.400000,4.004123,0.00,0.0,76.880000,47.030000
26,26,914.490000,49.892000,163.000000,4.854160,189.600000,6.733189,0.00,0.0,92.100000,90.990000
27,27,914.900000,78.620000,203.300000,1.811921,240.000000,2.751436,0.00,220.0,47.890000,43.900000
28,28,915.840000,40.118000,171.900000,10.535987,188.000000,12.929513,0.00,0.0,86.430000,84.390000
29,29,916.310000,45.428000,183.100000,8.343786,194.600000,10.088599,0.00,0.0,86.150000,90.580000
...,...,...,...,...,...,...,...,...,...,...,...
1065,1065,915.600000,69.584000,185.500000,4.630466,198.200000,5.480503,0.00,0.0,28.970000,39.370000
1066,1066,919.564869,73.726732,68.704694,3.551777,102.571616,4.861315,NaN,0.0,11.657314,17.331823
1067,1067,917.690000,64.994000,178.300000,2.975130,193.900000,3.735690,0.00,0.0,54.880000,52.070000
1068,1068,920.330000,68.864000,122.400000,2.035615,182.000000,3.086977,0.00,0.0,52.380000,62.620000
1069,1069,918.260000,82.220000,186.600000,1.096101,221.500000,1.722444,0.00,0.0,32.460000,56.930000
1070,1070,911.600000,46.346000,110.200000,2.304048,96.100000,3.154085,0.00,0.0,90.510000,62.490000
1071,1071,919.200000,70.250000,156.700000,2.013246,172.300000,2.617220,0.00,0.0,42.060000,41.850000
1072,1072,923.100000,75.596000,178.300000,1.409272,205.200000,1.856660,0.00,0.0,11.880000,19.810000
1073,1073,917.920000,84.650000,30.000000,4.831790,40.100000,5.838413,0.00,0.0,16.220000,27.450000
1074,1074,913.870000,66.938000,171.900000,6.509495,182.300000,7.471380,0.00,0.0,57.430000,53.380000
1075,1075,922.858110,64.989361,63.483047,10.261187,73.170504,11.949206,0.00,0.0,14.525109,15.511157
1076,1076,925.550000,50.918000,32.600000,5.413395,57.500000,8.120092,0.00,10.0,29.090000,23.720000
1077,1077,920.130000,73.292000,193.600000,4.115970,211.300000,4.966007,0.00,0.0,33.520000,38.120000
1078,1078,924.017856,68.370307,56.304083,15.162800,76.585117,19.803578,0.00,0.0,11.599240,9.373013
1079,1079,917.200000,65.264000,137.600000,1.767183,176.700000,2.550112,0.00,0.0,58.370000,65.590000
1080,1080,916.260000,79.772000,185.700000,3.511996,201.500000,4.160708,0.00,0.0,27.680000,20.400000
1081,1081,920.856913,69.884338,47.335966,12.238670,66.729162,16.067860,0.00,0.0,11.956852,12.696233
1082,1082,916.130000,50.108000,211.400000,2.550112,231.800000,3.534365,0.00,0.0,89.800000,53.860000
1083,1083,916.320000,48.308000,46.900000,4.854160,61.700000,5.860783,0.00,0.0,91.030000,62.400000
1084,1084,917.130000,80.240000,183.300000,1.632966,38.500000,2.259309,0.00,0.0,28.260000,34.690000
1085,1085,914.840000,47.354000,190.900000,3.713320,204.400000,4.652835,0.00,0.0,92.300000,88.160000
1086,1086,921.260000,52.646000,261.900000,2.035615,260.500000,3.042238,0.00,0.0,91.110000,81.890000
1087,1087,914.000000,66.650000,173.800000,8.366156,181.000000,9.439887,0.00,0.0,30.920000,47.340000
1088,1088,912.900000,71.870000,129.200000,1.431642,160.000000,2.057985,0.00,0.0,51.840000,55.490000
1089,1089,915.000000,55.040000,191.800000,5.368656,220.900000,7.068730,0.00,0.0,73.550000,69.670000
1090,1090,918.900000,63.104000,192.900000,3.869906,207.300000,5.212070,0.00,0.0,26.020000,38.180000
1091,1091,918.710000,49.568000,241.600000,1.811921,227.400000,2.371156,0.00,0.0,90.350000,73.340000
1092,1092,916.600000,71.096000,189.300000,3.064608,200.800000,3.892276,0.00,0.0,45.590000,52.310000
1093,1093,912.600000,58.406000,172.700000,3.825167,189.100000,4.764682,0.00,0.0,64.840000,58.280000
1094,1094,921.530000,77.702000,97.100000,3.265932,125.900000,4.451511,0.00,0.0,14.560000,15.100000

We observe that some of the cells have missing values, denoted as 'NaN'. Since it's impossible to see how many of those exist by visually exploring the dataset, we instead print out a total count of the non-empty cells for each attribute.

In [3]:
df.count()

number                    1095
air_pressure_9am          1092
air_temp_9am              1090
avg_wind_direction_9am    1091
avg_wind_speed_9am        1092
max_wind_direction_9am    1092
max_wind_speed_9am        1091
rain_accumulation_9am     1089
rain_duration_9am         1092
relative_humidity_9am     1095
relative_humidity_3pm     1095
dtype: int64

We observce that indeed, most of the attributes have missing values. 

We can also view the summary statistics.

In [4]:
df.describe()

#or for an alternative view...
#df.describe().transpose()

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
count,1095.000000,1092.000000,1090.000000,1091.000000,1092.000000,1092.000000,1091.000000,1089.000000,1092.000000,1095.000000,1095.000000
mean,547.000000,918.882551,64.933001,142.235511,5.508284,148.953518,7.019514,0.203079,294.108052,34.241402,35.344727
std,316.243577,3.184161,11.175514,69.137859,4.552813,67.238013,5.598209,1.593952,1598.078779,25.472067,22.524079
min,0.000000,907.990000,36.752000,15.500000,0.693451,28.900000,1.185578,0.000000,0.000000,6.090000,5.300000
25%,273.500000,916.550000,57.281000,65.972506,2.248768,76.553003,3.067477,0.000000,0.000000,15.092243,17.395000
50%,547.000000,918.921045,65.715479,166.000000,3.871333,177.300000,4.943637,0.000000,0.000000,23.179259,24.380000
75%,820.500000,921.160073,73.450974,191.000000,7.337163,201.233153,8.947760,0.000000,0.000000,45.400000,52.060000
max,1094.000000,929.320000,98.906000,343.400000,23.554978,312.200000,29.840780,24.020000,17704.000000,92.620000,92.250000


Time to do something about all these missing values.

Let's look closer at one variable, 'air_temp_9am':

In [5]:
df['air_temp_9am'].describe()

count    1090.000000
mean       64.933001
std        11.175514
min        36.752000
25%        57.281000
50%        65.715479
75%        73.450974
max        98.906000
Name: air_temp_9am, dtype: float64

In [6]:
#nill


One approach is to drop the rows that contain the missing values.

(notice that in order to avoid messing up with our original dataframe, we save the resulting dataset in a new dataframe df2)

In [7]:
df2 = df.dropna(subset=['air_temp_9am'])

Now let's see the total number of rows.

In [8]:
df2.count()

number                    1090
air_pressure_9am          1087
air_temp_9am              1090
avg_wind_direction_9am    1086
avg_wind_speed_9am        1087
max_wind_direction_9am    1087
max_wind_speed_9am        1086
rain_accumulation_9am     1084
rain_duration_9am         1087
relative_humidity_9am     1090
relative_humidity_3pm     1090
dtype: int64

Now let's clear the entire data frame from missing values.

In [9]:
df3 = df.dropna()
df3.count()

number                    1064
air_pressure_9am          1064
air_temp_9am              1064
avg_wind_direction_9am    1064
avg_wind_speed_9am        1064
max_wind_direction_9am    1064
max_wind_speed_9am        1064
rain_accumulation_9am     1064
rain_duration_9am         1064
relative_humidity_9am     1064
relative_humidity_3pm     1064
dtype: int64

How was the dataset affected by this? Let's look at the mean and standard deviation of the attributes.

In [10]:
df3.describe()

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
count,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000,1064.000000
mean,545.001880,918.903180,65.022609,142.306756,5.485793,148.480424,6.999714,0.182023,266.393697,34.077440,35.148381
std,316.796111,3.179040,11.168033,69.149472,4.534427,67.154911,5.590790,1.534493,1503.092216,25.356668,22.365475
min,0.000000,907.990000,36.752000,15.500000,0.693451,28.900000,1.185578,0.000000,0.000000,6.090000,5.300000
25%,269.750000,916.595376,57.398000,65.979244,2.245529,76.335351,3.064608,0.000000,0.000000,15.093365,17.360468
50%,543.500000,918.942281,65.778479,165.937461,3.869906,176.350000,4.943637,0.000000,0.000000,23.135000,24.371286
75%,819.250000,921.169054,73.530872,191.100000,7.264463,201.125000,8.747888,0.000000,0.000000,44.660000,51.922500
max,1094.000000,929.320000,98.906000,343.400000,23.554978,312.200000,29.840780,24.020000,17704.000000,92.620000,92.250000

Imputation

An alternative approach to missing values is to impute them. 

The following snippet demonstrates how to replace missing values, encoded as np.nan, using the mean value of the column (axis 0) that contain the missing values.

In [11]:
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
imputed_DF = pd.DataFrame(imp.fit_transform(df))
imputed_DF.columns = df.columns
imputed_DF.index = df.index

Now let's see how much did the attributes' stats change...

In [12]:
imputed_DF.describe()

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
count,1095.000000,1095.000000,1095.000000,1095.000000,1095.000000,1095.000000,1095.000000,1095.000000,1095.000000,1095.000000,1095.000000
mean,547.000000,918.882551,64.933001,142.235511,5.508284,148.953518,7.019514,0.203079,294.108052,34.241402,35.344727
std,316.243577,3.179792,11.149947,69.011349,4.546567,67.145759,5.587965,1.589575,1595.886124,25.472067,22.524079
min,0.000000,907.990000,36.752000,15.500000,0.693451,28.900000,1.185578,0.000000,0.000000,6.090000,5.300000
25%,273.500000,916.565752,57.353000,66.109634,2.254120,76.663570,3.077758,0.000000,0.000000,15.092243,17.395000
50%,547.000000,918.900000,65.678000,165.736408,3.891117,177.000000,4.956648,0.000000,0.000000,23.179259,24.380000
75%,820.500000,921.160000,73.435920,190.900000,7.325978,201.150000,8.872373,0.000000,0.000000,45.400000,52.060000
max,1094.000000,929.320000,98.906000,343.400000,23.554978,312.200000,29.840780,24.020000,17704.000000,92.620000,92.250000

In [13]:
#assignment question 3
df['rain_accumulation_9am'].describe()

count    1089.000000
mean        0.203079
std         1.593952
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max        24.020000
Name: rain_accumulation_9am, dtype: float64